### Register new user
POST http://localhost:3001/userRegistration
content-type: application/json

{
    "newUser": {
        "firstName": "John",
        "lastName": "Smith",
        "userName": "the_spaniard",
        "password": "Spaniard123",
        "email": "jsmith@aol.com",
        "phoneNumber": 8015550000,
        "address": "123 S 456 E SLC, UT"
    }
}
#### login request
POST http://localhost:3001/studentLogin
content-type: application/json

{
    "Credentials": {
        "username": "the_prophet",
        "password": "GoldenPlates123"
    }
}

### logout request
DELETE http://localhost:3001/logout
content-type: application/json

### get courses for specific user
GET http://localhost:3001/courses/allCourses
content-type: application/json

### get current user's enrolled courses
GET http://localhost:3001/courses/enrolledCourses?classId=CSCI-2001
content-type: application/json


### enroll standard user in an existing course
POST http://localhost:3001/courses/enroll
content-type: application/json

{
    "something": "blah"
}
